services:
  unified_container:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: unified_container
    container_name: unified_container
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
    volumes:
      - ./.env:/app/.env:ro
      - ./logs:/app/logs:rw
      - ./app/media:/app/app/media:rw
    env_file:
      - .env
    restart: unless-stopped